MYLIB =  $(LIBDIR)
                                                                                                             
.c.a:
	gcc -c $<
	ar rv $@ $*.o
	rm -f $*.o
MAKE = make
                                                                                                                                                       
$(MYLIB)/libPICK.a: \
	$(MYLIB)/libPICK.a(julian.o) \
	$(MYLIB)/libPICK.a(starttime.o) \
	$(MYLIB)/libPICK.a(TTtimes.o) \
	$(MYLIB)/libPICK.a(TTtables.o) \
	$(MYLIB)/libPICK.a(strspace.o) \
	$(MYLIB)/libPICK.a(finddeps.o) \
	$(MYLIB)/libPICK.a(extractTTime.o) \
	$(MYLIB)/libPICK.a(epdist.o) \
	$(MYLIB)/libPICK.a(check_xh.o) \
	$(MYLIB)/libPICK.a(signallevel.o) \
	$(MYLIB)/libPICK.a(resample.o) \
	$(MYLIB)/libPICK.a(processing.o) \
	$(MYLIB)/libPICK.a(L2fit.o) \
	$(MYLIB)/libPICK.a(write_review1.o) \
	$(MYLIB)/libPICK.a(write_review_sp.o) \
	$(MYLIB)/libPICK.a(write_review_ps.o) \
	$(MYLIB)/libPICK.a(noiselevel.o) \
	$(MYLIB)/libPICK.a(measure_P.o) \
	$(MYLIB)/libPICK.a(measure_pP.o) \
	$(MYLIB)/libPICK.a(measure_sP.o) \
	$(MYLIB)/libPICK.a(measure_PP.o) \
	$(MYLIB)/libPICK.a(measure_PPP.o) \
	$(MYLIB)/libPICK.a(measure_PKP.o) \
	$(MYLIB)/libPICK.a(measure_PKIKP.o) \
	$(MYLIB)/libPICK.a(measure_S.o) \
	$(MYLIB)/libPICK.a(measure_SV.o) \
	$(MYLIB)/libPICK.a(measure_SZ.o) \
	$(MYLIB)/libPICK.a(measure_sS.o) \
	$(MYLIB)/libPICK.a(measure_SS.o) \
	$(MYLIB)/libPICK.a(measure_sSS.o) \
	$(MYLIB)/libPICK.a(measure_SSS.o) \
	$(MYLIB)/libPICK.a(measure_ScS.o) \
	$(MYLIB)/libPICK.a(measure_sScS.o) \
	$(MYLIB)/libPICK.a(measure_ScSScS.o) \
	$(MYLIB)/libPICK.a(measure_sScSScS.o) \
	$(MYLIB)/libPICK.a(measure_SKS.o) \
	$(MYLIB)/libPICK.a(measure_sSKS.o) \
	$(MYLIB)/libPICK.a(measure_SKKS.o) \
	$(MYLIB)/libPICK.a(measure_PS.o) \
	$(MYLIB)/libPICK.a(measure_SP.o)
	ranlib $(MYLIB)/libPICK.a
