LIBDIR=$(HOME)/src/lib
LIB =libcmt_sun

include	$(HOME)/etc/Makerules_sun

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(findcmtlocndk.o) \
	$(LIBDIR)/$(LIB).a(ndkread.o) \
	$(LIBDIR)/$(LIB).a(findcmtsim.o) \
	$(LIBDIR)/$(LIB).a(puttim.o) \

include	$(HOME)/etc/Makeranlib
